# Generated by Django 2.2 on 2019-10-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appendix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文件名')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='上传日期')),
                ('task_id', models.IntegerField()),
                ('publisher', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
            options={
                'permissions': {('edit_appendix', '编辑附件')},
            },
        ),
        migrations.CreateModel(
            name='personal_appendix',
            fields=[
                ('detail', models.TextField(default='[]', verbose_name='私人附件详情')),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '私人附件',
                'verbose_name_plural': '私人附件',
                'permissions': {('download_personal_appendix', '下载私人附件'), ('edit_personal_appendix', '编辑私人附件'), ('upload_personal_appendix', '下载私人附件')},
            },
        ),
    ]
